Repository cashubtc/eNuts, pull requests merged in 2023-06, with the labels that each got.

#17 add shim & remove pkg patches
  package-lock.json
  package.json
  patches/@noble+hashes+1.3.0.patch
  src/shim.ts
  src/storage/store/HistoryStore.ts
  src/storage/store/SimpleKeyValueStore.ts
  src/util/index.ts
  src/util/typeguards.ts
  typings/bolt11.d.ts
Labels: enhancement

#18 Fix QR
  src/components/Balance.tsx
  src/components/QR.tsx
Labels: enhancement

#21 add localization helper & update @styles imports
  config/app.config.ts
  package-lock.json
  package.json
  src/AppEntry.ts
  src/components/App.tsx
  src/components/Backup.tsx
  src/components/Balance.tsx
  src/components/Button.tsx
  src/components/InvoiceAmount.tsx
  src/components/Success.tsx
  src/components/Txt.tsx
  src/components/coinSelectionRow.tsx
  src/components/modal/OptsModal.tsx
  src/components/modal/Prompt.tsx
  src/components/modal/Question.tsx
  src/components/modal/TrustMint.tsx
  src/components/modal/index.tsx
  src/components/nav/BottomNav.tsx
  src/components/nav/CustomDrawer.tsx
  src/components/nav/TopNav.tsx
  src/components/pages/Addressbook/Book.tsx
  src/components/pages/Addressbook/Contact.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/EncodedToken.tsx
  src/components/pages/History/Details.tsx
  src/components/pages/History/Entry.tsx
  src/components/pages/History/index.tsx
  src/components/pages/Lightning/mintPanel.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Lightning/pageContent.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/Info.tsx
  src/components/pages/Mints/IntermintSwap.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/Settings/Display.tsx
  src/components/pages/Settings/Security.tsx
  src/components/pages/Settings/index.tsx
  src/components/pages/Success.tsx
  src/context/Theme.tsx
  src/shim.ts
  src/styles/index.ts
  src/util/index.ts
  src/util/localization.ts
Labels: enhancement

#22 add openLinkInBrowser helper && update jest setup
  .github/workflows/node.js.yml
  config/jest.config.ts
  package-lock.json
  package.json
  src/components/Balance.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/util/index.ts
  test/HistoryStore.test.ts
  test/SimpleKeyValueStore.test.ts
  test/db.test.ts
  test/setup.ts
Labels: enhancement, Test, CI

#24 Show custom mint names in pickers
  src/components/pages/History/Entry.tsx
  src/components/pages/Lightning/index.tsx
  src/components/pages/Lightning/mintPanel.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Lightning/pageContent.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/IntermintSwap.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/Send.tsx
  src/consts/mints.ts
  src/model/index.ts
  src/model/nav.ts
  src/storage/store/mintStore.ts
  src/util/index.ts
Labels: enhancement

#25 Cashu token memo
  src/components/App.tsx
  src/components/Success.tsx
  src/components/Toaster.tsx
  src/components/hooks/Prompt.tsx
  src/components/pages/Addressbook/Book.tsx
  src/components/pages/Addressbook/Contact.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/History/Entry.tsx
  src/components/pages/Lightning/mintPanel.tsx
  src/components/pages/Lightning/pageContent.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/QRScan.tsx/index.tsx
  src/components/pages/Send.tsx
  src/components/pages/Success.tsx
  src/model/nav.ts
  src/styles/globals.ts
  src/util/index.ts
  src/wallet/index.ts
Labels: enhancement

#27 update sql stuff
  src/components/pages/Lightning/index.tsx
  src/components/pages/Lightning/mintPanel.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Lightning/pageContent.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/Info.tsx
  src/components/pages/Mints/IntermintSwap.tsx
  src/components/pages/Mints/MintBackup.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/Send.tsx
  src/consts/mints.ts
  src/model/index.ts
  src/model/nav.ts
  src/storage/db/Db.ts
  src/storage/db/backup.ts
  src/storage/db/index.ts
  src/storage/db/sql/table.ts
  src/storage/db/sql/view.ts
  src/storage/store/mintStore.ts
  src/util/index.ts
  src/wallet/index.ts
  test/db.test.ts
Labels: enhancement, DB, Test

#28 3 add a mint option to show proofs
  src/components/App.tsx
  src/components/Icons.tsx
  src/components/coinSelectionRow.tsx
  src/components/nav/BottomNav.tsx
  src/components/nav/Navigator.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/Proofs.tsx
  src/model/nav.ts
Labels: enhancement

#30 setup bugsnag & add ErrorBoundary
  .gitignore
  app.config.js
  babel.config.js
  config/app.config.ts
  metro.config.js
  package-lock.json
  package.json
  react-native.config.js
  src/AppEntry.ts
  src/components/App.tsx
  src/components/Success.tsx
  src/components/pages/History/entryTime.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/QRScan.tsx/index.tsx
  src/consts/env.ts
  src/consts/index.ts
  src/consts/mints.ts
  src/consts/qr.ts
  src/consts/time.ts
  src/logger/index.ts
  src/model/index.ts
  src/util/crashReporting.ts
  src/wallet/index.ts
  test/setup.ts
Labels: enhancement, Android, dependencies

#32 Update the cashu token QR
  src/components/pages/EncodedToken.tsx
  src/wallet/index.ts
Labels: enhancement

#34 update getMintsUrls
  src/components/pages/Lightning/index.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/Send.tsx
  src/storage/db/index.ts
  src/util/index.ts
  src/wallet/index.ts
Labels: enhancement, DB

#35 [Feature request] "eCash" -> "Ecash" The 90s are long gone!!! 😁
  src/components/pages/History/Details.tsx
  src/components/pages/History/Entry.tsx
Labels: bug, documentation, enhancement, styling

#36 add jscpd & add @consts path alias
  .eslintignore
  .gitignore
  config/babel.config.ts
  config/cpd.config.ts.json
  config/cpd.config.tsx.json
  config/jest.config.ts
  package.json
  src/AppEntry.ts
  src/components/App.tsx
  src/components/ErrorScreen/ErrorBoundary.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/Success.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/History/entryTime.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/QRScan.tsx/index.tsx
  src/consts/env.ts
  src/logger/index.ts
  src/logger/reactotron/index.ts
  src/logger/reactotron/reactotron.ts
  src/logger/reactotron/reactotronClient.ts
  src/logger/reactotron/reactotronConfig.ts
  src/logger/reactotron/reactotronFake.ts
  src/util/crashReporting.ts
  src/util/index.ts
  src/util/typeguards.ts
  test/AsyncStore.test.ts
  test/HistoryStore.test.ts
  test/SimpleKeyValueStore.test.ts
  test/db.test.ts
  test/setup.ts
  test/utils.test.ts
  test/wrapper/getTestDb.ts
  tsconfig.json
Labels: duplicate, enhancement, dependencies

#39 success component basic test
  .eslintignore
  .eslintrc.json
  config/jest.config.tsx.ts
  package-lock.json
  package.json
  test/AsyncStore.test.ts
  test/HistoryStore.test.ts
  test/SimpleKeyValueStore.test.ts
  test/components/Balance.test.tsx
  test/components/Success.test.tsx
  test/components/Txt.test.tsx
  test/db.test.ts
  test/setup.ts
  test/utils.test.ts
Labels: Test

#40 update lint & update Success component navigation test
  .eslintrc.json
  config/jest.config.ts
  package-lock.json
  package.json
  src/components/Balance.tsx
  src/components/Button.tsx
  src/components/ErrorScreen/ErrorBoundary.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/InvoiceAmount.tsx
  src/components/Success.tsx
  src/components/modal/TrustMint.tsx
  src/components/nav/BottomNav.tsx
  src/components/nav/Navigator.tsx
  src/components/nav/TopNav.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/QRScan.tsx/index.tsx
  src/components/pages/Send.tsx
  src/components/pages/Success.tsx
  src/context/Keyboard.tsx
  test/components/Success.test.tsx
  test/setup.ts
Labels: enhancement, dependencies, Test, CI

#41 33 indicate keyset ids with a font color
  src/components/App.tsx
  src/components/Icons.tsx
  src/components/InvoiceAmount.tsx
  src/components/KeysetHint.tsx
  src/components/Success.tsx
  src/components/coinSelectionRow.tsx
  src/components/modal/TrustMint.tsx
  src/components/pages/Addressbook/Contact.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/History/entryTime.tsx
  src/components/pages/Lightning/index.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Lightning/pageContent.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/Info.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/Proofs.tsx
  src/wallet/index.ts
Labels: enhancement, styling

#42 add getMintCurrentKeySetId & getMintKeySetIds fns
  package.json
  src/components/App.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Mints/Proofs.tsx
  src/consts/env.ts
  src/logger/index.ts
  src/storage/db/index.ts
  src/wallet/index.ts
Labels: enhancement

#43 Bugsnag
  .example.env.dev
  src/components/App.tsx
  src/components/Balance.tsx
  src/components/ErrorScreen/ErrorBoundary.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/pages/Dashboard.tsx
  src/consts/urls.ts
Labels: bug, documentation, enhancement

#45 Add options to the history entry of an ecash tx #20
  .github/release.yml
  package.json
  src/components/nav/CustomDrawer.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/History/Details.tsx
Labels: enhancement

#46 update eas ci workflow
  .github/workflows/eas.yml
  config/app.config.ts
  package-lock.json
  package.json
Labels: enhancement, CI, ignore-for-release

#48 add updateHistoryEntry
  src/storage/store/HistoryStore.ts
  src/storage/store/StoreBase.ts
  test/HistoryStore.test.ts
Labels: enhancement, DB, test

#50 Bugfix
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/pages/History/Details.tsx
  src/model/index.ts
Labels: bug, enhancement

#52 Fix app crashes after autofocus of LNURL amount input. Define bugsnag component outside of app component to avoid subtree's DOM nodes and states beeing destroyed
  .github/release.yml
  app.config.js
  config/app.config.ts
  package.json
  src/AppEntry.ts
  src/components/App.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/InvoiceAmount.tsx
  src/components/nav/CustomDrawer.tsx
  src/components/pages/History/Details.tsx
  src/components/pages/Lightning/modal.tsx
  src/components/pages/Lightning/pageContent.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/IntermintSwap.tsx
  src/util/index.ts
  src/wallet/index.ts
Labels: bug

#60 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, ignore-for-release

#62 update README.md
  README.md
Labels: documentation, enhancement

#63 update adaptive-icon
  assets/adaptive-icon-.png
  assets/adaptive-icon.png
Labels: bug, Android, IOS

#65 Update navigation
  src/components/App.tsx
  src/components/Icons.tsx
  src/components/nav/BottomNav.tsx
  src/components/nav/CustomDrawer.tsx
  src/components/nav/Navigator.tsx
  src/components/nav/TopNav.tsx
  src/model/nav.ts
  src/styles/colors.ts
  src/styles/globals.ts
  typings/nav.d.ts
Labels: enhancement, styling, release

#66 Reusable
  src/components/InitialModal.tsx
  src/components/Separator.tsx
  src/components/pages/Addressbook/Book.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/History/Details.tsx
  src/components/pages/History/index.tsx
  src/components/pages/Mints/Info.tsx
  src/components/pages/Settings/Display.tsx
  src/components/pages/Settings/index.tsx
  src/styles/globals.ts
Labels: enhancement, release

#67 add screen titles to the top navbar
  src/components/pages/Addressbook/index.tsx
  src/components/pages/History/Details.tsx
  src/components/pages/History/index.tsx
  src/components/pages/Lightning/index.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Mints/IntermintSwap.tsx
  src/components/pages/Mints/MintBackup.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/Proofs.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/Send.tsx
  src/components/pages/Settings/Backup.tsx
  src/components/pages/Settings/Display.tsx
  src/components/pages/Settings/Security.tsx
  src/components/pages/Settings/index.tsx
Labels: styling

#64 fix: display 'add a new mint' modal when keyboard is open
  .eslintrc.json
  src/components/modal/index.tsx
Labels: bug, IOS, release

#69 Update dashboard layout
  src/components/pages/Dashboard.tsx
Labels: styling

#68 Proofs screen: improve huge proof list using flashlist, update layout
  src/components/pages/Mints/Proofs.tsx
  src/styles/globals.ts
Labels: enhancement, release

#70 Use Toaster instead of popup, update prompt hook. Fixes #9
  src/components/App.tsx
  src/components/Button.tsx
  src/components/hooks/Prompt.tsx
  src/components/pages/Addressbook/Book.tsx
  src/components/pages/Addressbook/Contact.tsx
  src/components/pages/Dashboard.tsx
  src/components/pages/Lightning/payInvoice.tsx
  src/components/pages/Lightning/scannedQR.tsx
  src/components/pages/Mints/MintManagement.tsx
  src/components/pages/Mints/index.tsx
  src/components/pages/QRScan.tsx/index.tsx
  src/components/pages/Settings/Security.tsx
  src/components/pages/Settings/index.tsx
Labels: styling

#73 Update README.md
  README.md
Labels: documentation

#72 Add keyboardAvoidingView. Fixes #8
  src/components/InvoiceAmount.tsx
  src/components/modal/index.tsx
  src/components/screens/Addressbook/Contact.tsx
  src/components/screens/Lightning/payInvoice.tsx
  src/consts/env.ts
Labels: bug

#79 add onRequestClose prop to Modal
  src/components/App.tsx
  src/components/InitialModal.tsx
  src/components/modal/OptsModal.tsx
  src/components/modal/Question.tsx
  src/components/modal/TrustMint.tsx
  src/components/modal/index.tsx
  src/components/screens/Addressbook/Book.tsx
  src/components/screens/Addressbook/Contact.tsx
  src/components/screens/Addressbook/modal.tsx
  src/components/screens/History/Details.tsx
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Lightning/scannedQR.tsx
  src/components/screens/Mints/MintManagement.tsx
  src/components/screens/Mints/index.tsx
Labels: enhancement

#76 Small style fixes and update new contact state
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/Button.tsx
  src/components/InitialModal.tsx
  src/components/modal/OptsModal.tsx
  src/components/modal/Question.tsx
  src/components/modal/TrustMint.tsx
  src/components/modal/index.tsx
  src/components/screens/Addressbook/Book.tsx
  src/components/screens/Addressbook/Contact.tsx
  src/components/screens/Addressbook/modal.tsx
  src/components/screens/History/Details.tsx
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Lightning/scannedQR.tsx
  src/components/screens/Mints/MintManagement.tsx
  src/components/screens/Mints/index.tsx
Labels: enhancement, dependencies

#82 Update README.md
  README.md
  package.json
Labels: documentation, dependencies

#86 0.0.5 alpha
  assets/adaptive-icon.png
  assets/appName.png
  assets/appName_dark.png
  assets/icon.png
  assets/icon_transparent_dark.png
  assets/logo_transparent.png
  assets/qr-icon.png
  config/app.config.ts
  package-lock.json
  package.json
  src/components/QR.tsx
  src/components/modal/index.tsx
  src/components/screens/Addressbook/modal.tsx
  src/components/screens/Lightning/modal.tsx
  test/components/AddressBook.test.tsx
  test/components/CoinSelectionModal.test.tsx
Labels: bug, test

#87 Minor fixes
  README.md
  assets/adaptive-icon.png
  config/app.config.ts
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Mints/Proofs.tsx
Labels: bug, documentation, styling

#89 add pnpm
  .eslintignore
  .eslintrc.json
  .github/workflows/eas.yml
  .github/workflows/node.js.yml
  .npmrc
  README.md
  config/app.config.ts
  config/jest.config.ts
  config/metro.config.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/ErrorScreen/ErrorBoundary.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/Success.tsx
  src/components/modal/index.tsx
  src/components/nav/Navigator.tsx
  src/components/screens/Dashboard.tsx
  src/components/screens/Lightning/pageContent.tsx
  src/components/screens/QRScan/Marker.tsx
  src/components/screens/QRScan/index.tsx
  src/consts/env.ts
  src/consts/index.ts
  src/context/Linking.tsx
  src/context/Theme.tsx
  src/logger/reactotron/index.ts
  src/logger/reactotron/reactotron.ts
  src/model/nav.ts
  src/storage/store/StoreBase.ts
  src/styles/index.ts
  src/util/crashReporting.ts
  src/util/index.ts
  src/wallet/proofs.ts
  src/wallet/util.ts
  test/components/Success.test.tsx
  test/setup.ts
  typings/bolt11.d.ts
  typings/nav.d.ts
Labels: enhancement, dependencies, styling, test, CI

#88 fix: not navigating to the scan-QR
  src/components/screens/Addressbook/index.tsx
  src/components/screens/Lightning/pageContent.tsx
  src/components/screens/Settings/index.tsx
  test/components/AddressBook.test.tsx
  test/components/Balance.test.tsx
  test/components/CoinSelectionModal.test.tsx
Labels: bug

#74 enhancement: show an error message if openLink fails
  src/components/Balance.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Lightning/payInvoice.tsx
  src/util/index.ts
Labels: enhancement

#93 12 add translations 🌐
  .github/workflows/node.js.yml
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/fr.json
  package-lock.json
  package.json
  src/AppEntry.ts
  src/components/App.tsx
  src/components/Backup.tsx
  src/components/Balance.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/Icons.tsx
  src/components/InitialModal.tsx
  src/components/InvoiceAmount.tsx
  src/components/Success.tsx
  src/components/coinSelectionRow.tsx
  src/components/modal/OptsModal.tsx
  src/components/modal/Question.tsx
  src/components/modal/TrustMint.tsx
  src/components/nav/BottomNav.tsx
  src/components/nav/Navigator.tsx
  src/components/nav/TopNav.tsx
  src/components/screens/Addressbook/Book.tsx
  src/components/screens/Addressbook/Contact.tsx
  src/components/screens/Addressbook/index.tsx
  src/components/screens/Dashboard.tsx
  src/components/screens/EncodedToken.tsx
  src/components/screens/History/Details.tsx
  src/components/screens/History/Entry.tsx
  src/components/screens/History/entryTime.tsx
  src/components/screens/History/index.tsx
  src/components/screens/Lightning/index.tsx
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Lightning/pageContent.tsx
  src/components/screens/Lightning/payInvoice.tsx
  src/components/screens/Lightning/scannedQR.tsx
  src/components/screens/Mints/Info.tsx
  src/components/screens/Mints/IntermintSwap.tsx
  src/components/screens/Mints/MintBackup.tsx
  src/components/screens/Mints/MintManagement.tsx
  src/components/screens/Mints/index.tsx
  src/components/screens/QRScan/index.tsx
  src/components/screens/Send.tsx
  src/components/screens/Settings/Backup.tsx
  src/components/screens/Settings/Display.tsx
  src/components/screens/Settings/Language.tsx
  src/components/screens/Settings/Security.tsx
  src/components/screens/Settings/index.tsx
  src/context/Linking.tsx
  src/i18n.ts
  src/model/nav.ts
  src/storage/store/SimpleKeyValueStore.ts
  test/components/Balance.test.tsx
  test/components/CoinSelectionModal.test.tsx
  test/setup.ts
Labels: enhancement, release
