Repository cashubtc/eNuts, pull requests merged in 2023-07, with the labels that each got.

#99 update README.md, add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#100 added about screen
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/fr.json
  src/components/Icons.tsx
  src/components/nav/Navigator.tsx
  src/components/screens/Settings/About.tsx
  src/components/screens/Settings/index.tsx
  src/model/nav.ts
Labels: documentation, enhancement

#106 Switch to Sentry
  .example.env.dev
  .gitignore
  config/app.config.ts
  eas.json
  package-lock.json
  package.json
  src/AppEntry.ts
  src/components/App.tsx
  src/components/ErrorScreen/ErrorBoundary.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/consts/env.ts
  src/model/index.ts
  src/util/crashReporting.ts
  test/setup.ts
Labels: enhancement, Android, IOS, dependencies, test, CI, DX

#104 Add user PIN authentication 🔒
  assets/adaptive-icon.png
  assets/app-icon-all.png
  assets/app-icon-android-adaptive-background.png
  assets/app-icon-android-adaptive-foreground.png
  assets/app-icon-android-legacy.png
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/fr.json
  config/app.config.ts
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/Icons.tsx
  src/components/QR.tsx
  src/components/nav/Navigator.tsx
  src/components/nav/TopNav.tsx
  src/components/screens/Auth/Hint.tsx
  src/components/screens/Auth/PinDots.tsx
  src/components/screens/Auth/PinPad.tsx
  src/components/screens/Auth/index.tsx
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Lightning/payInvoice.tsx
  src/components/screens/Lightning/scannedQR.tsx
  src/components/screens/Settings/Language.tsx
  src/components/screens/Settings/Security.tsx
  src/consts/time.ts
  src/context/Pin.tsx
  src/model/nav.ts
  src/storage/store/SimpleKeyValueStore.ts
  src/storage/store/StoreBase.ts
  src/storage/store/index.ts
  src/util/crypto/utils.ts
  src/util/index.ts
Labels: enhancement

#113 added type-safe i18next - fix minor spelling, styling and translation issues
  assets/translations/de.json
  assets/translations/en.json
  assets/translations/fr.json
  config/app.config.ts
  package-lock.json
  package.json
  src/AppEntry.ts
  src/components/App.tsx
  src/components/Backup.tsx
  src/components/Balance.tsx
  src/components/ErrorScreen/ErrorDetails.tsx
  src/components/InitialModal.tsx
  src/components/InvoiceAmount.tsx
  src/components/Success.tsx
  src/components/modal/OptsModal.tsx
  src/components/modal/Question.tsx
  src/components/modal/TrustMint.tsx
  src/components/nav/BottomNav.tsx
  src/components/nav/TopNav.tsx
  src/components/screens/Addressbook/Book.tsx
  src/components/screens/Addressbook/Contact.tsx
  src/components/screens/Addressbook/index.tsx
  src/components/screens/Auth/Hint.tsx
  src/components/screens/Auth/PinPad.tsx
  src/components/screens/Auth/index.tsx
  src/components/screens/Dashboard.tsx
  src/components/screens/EncodedToken.tsx
  src/components/screens/History/Details.tsx
  src/components/screens/History/Entry.tsx
  src/components/screens/History/entryTime.tsx
  src/components/screens/History/index.tsx
  src/components/screens/Lightning/index.tsx
  src/components/screens/Lightning/modal.tsx
  src/components/screens/Lightning/pageContent.tsx
  src/components/screens/Lightning/payInvoice.tsx
  src/components/screens/Lightning/scannedQR.tsx
  src/components/screens/Mints/Info.tsx
  src/components/screens/Mints/IntermintSwap.tsx
  src/components/screens/Mints/MintBackup.tsx
  src/components/screens/Mints/MintManagement.tsx
  src/components/screens/Mints/index.tsx
  src/components/screens/QRScan/index.tsx
  src/components/screens/Send.tsx
  src/components/screens/Settings/About.tsx
  src/components/screens/Settings/Backup.tsx
  src/components/screens/Settings/Display.tsx
  src/components/screens/Settings/Language.tsx
  src/components/screens/Settings/Security.tsx
  src/components/screens/Settings/index.tsx
  src/i18n.ts
  src/model/i18n.ts
  src/storage/store/index.ts
  src/styles/colors.ts
  src/util/localization.ts
  test/setup.ts
  typings/i18next.d.ts
Labels: bug, DX
